name: build
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go build -ldflags "-s -w" .

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          name: clicord_${{ runner.os }}_${{ runner.arch }}
          path: |
            clicord
            clicord.exe
